[tool.poetry]
name = "fastapi=temmplate"
version = "0.1.0"
description = "This is a FastAPI template project."
authors = ["Kanha Upadhyay <kanha.upadhyay@sifars.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
python-dotenv = "^1.0.1"
alembic = "^1.13.1"
greenlet = "^3.0.3"
asyncpg = "^0.29.0"
loguru = "^0.7.2"
filetype = "^1.2.0"
httpx = "^0.27.0"
aiofiles = "^24.1.0"
openai = "^1.51.0"
apscheduler = "^3.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
